### PR TITLE
use updated cloud vocabularies

### PR DESCRIPTION
**Pull request by marqh**
update examples to use planned updated cloud vocabularies

### CODE REVIEW

**Comment by mgoberfield** [comment]
Please proceed

**Comment by blchoy** [comment]
I think it is OK, but merging is pending the implementation of changes in the WMO Codes Registry.

**Comment by marqh** [comment]
@efucile 
merging this PR has propagated the failing tests onto the master branch

this was not out intent

**Comment by marqh** [comment]
the changes to the vocabulary server need to happen first, to avoid this problem

**Comment by marqh** [comment]
please may I 'revert' this, to keep the work flow clean?

**Pull request merged**
