### PR TITLE
Schematron rules merged into iwxxm.sch

### LINKED ISSUE #32: Combine iwxxm-collect.sch and iwxxm.sch
The contents of iwxxm-collect.sch and iwxxm.sch are almost identical.  It would be clearer and easier to combine these files as long as IWXXM messages by themselves validate with the extra COLLECT rule.  

If "unwrapped" IWXXM messages do not validate then either COLLECT Schematron can be changed or they should not be combined.

### LINKED ISSUE #60: Combine iwxxm.sch, iwxxm-collect.sch and rules for offline checking of WMO Code Registry contents
There are only minor differences between iwxxm.sch and iwxxm-collect.sch, essentially only a single COLLECT rule.  This rule (COLLECT.MB1) only takes action when a COLLECT element is used, which means that iwxxm-collect.sch is a drop-in replacement for iwxxm.sch.  Combine all Schematron files into a single iwxxm.sch file, which may be as simple as renaming iwxxm-collect.sch to iwxxm.sch.

### PR DESCRIPTION
**Pull request by braeckel**
Closes #60, Closes #32. Removed iwxxm-collect.sch and iwxxm-collect-codelists.sch.  Updated iwxxm.sch contents to include both Collect and Codelist-related rules, this single SCH file now includes the exact contents that used to be in iwxxm-collect-codelists.sch.  iwxxm-collect.sch only included a single additional rule which was only triggered against Collect messages (was safe to merge), and iwxxm-collect-codelists.sch had additional namespaces and CodeList rules that are now part of the IWXXM standard Schematron checks.

@blchoy 
Further changes to the CodeLists-related rules are probably necessary (for example, id names might be improved) but this can follow this PR and will be independent of the issues being addressed here.  The Schematron file more generally will also likely need to be regenerated/updated based upon recent changes such as #50 and #27, and the Schematron-generation process changes to generate only a single SCH file (instead of three) will need to be changed.  It is your call as to whether you would like to check in these changes as part of this PR or as a separate set of changes after this PR.

### CODE REVIEW

**Comment by braeckel** [comment]
The build failures will be resolved when this PR is merged, this was caused by Crux limitations that are resolved with Crux 1.3 (now the version on master)

**Comment by blchoy** [comment]
Would like to update the schematron generating XSLT before merging the PR.  I have made a suggestion in #60.

**Comment by braeckel** [comment]
My apologies, I just caught up to your last comment on this issue and I should not have merged this PR.  I'm not sure it is possible to reverse the merge, are you comfortable addressing this as part of the broader Schematron changes discussed here and elsewhere?

**Comment by blchoy** [comment]
No problem for the merge.  In fact we need to create another PR once we finished updating the schematrons rules.

**Pull request merged**
