### PR TITLE
Update schematron and METAR example for validation

### PR DESCRIPTION
**Pull request by mgoberfield**
Addresses #140 without addition of srsNames

### CODE REVIEW

**Comment by blchoy** [comment]
Thank you.  I am trying to list out all geospatial objects in IWXXM in the wiki page (https://github.com/wmo-im/iwxxm/wiki/Geospatial-objects-in-IWXXM) to make sure that we will not miss anything in the implementation.  May be we review and merge the PR after the study?

**Comment by mgoberfield** [comment]
Of course, Choy!  You are the benevolent dictator of the repository.  You
do not have to accept junk.

mark

**Comment by blchoy** [comment]
Hi @mgoberfield, I have listed out all geospatial objects in IWXXM in https://github.com/wmo-im/iwxxm/wiki/Geospatial-objects-in-IWXXM.  May I ask your kind assistant to take a look?  Feel free to edit.  Of course, some objects like iwxxm:tropicalCyclonePosition now seems to be necessary to have CRS included and we may need to update the examples accordingly.

**Comment by mgoberfield** [comment]
Hi Choy (@blchoy ),

I will get out my red pen and 🔍

**Comment by mgoberfield** [comment]
Initial sweep of the draft done, @blchoy.  I added the <metce:EruptingVolcano> case as it requires a 3-D CRS since the summit height of the volcano is not represented separately in the feature.

**Comment by blchoy** [comment]
> 
> 
> Initial sweep of the draft done, @blchoy. I added the metce:EruptingVolcano case as it requires a 3-D CRS since the summit height of the volcano is not represented separately in the feature.

Looks like a deficiency to me  :(  I may need to initiate an urgent fix to this.  Let's discuss later today during the TT-AvXML telecon.  @marqh please note.

**Comment by blchoy** [comment]
Thanks @mgoberfield for contributing.  I have extended your code on CRS checking in RC3 which will be made available in a separate PR.

**Pull request closed without merging**
