### PR TITLE
First commitment of IWXXM 2023-1RC1

### PR DESCRIPTION
**Pull request by blchoy**
This pull request incorporates changes to IWXXM 2021-2 with regard to:
1. iwxxm.sch bugs involving SIGMET (#293), and
2. The missing representation for airframe icing phenomenon in the WAFS SIGWX F/C package (#294)

### CODE REVIEW

**Review by mgoberfield — APPROVED** [review]

**Comment by jkorosi** [comment]
I have an additional question. Should be the maximum of supplementaryAnalysisCollection limited to 1?occurenes <element name="supplementaryAnalysisCollection" minOccurs="0" maxOccurs="1">

**Review by jkorosi — COMMENTED** [review]
Checked.

**Comment by blchoy** [comment]
> I have an additional question: Should the maximum of supplementaryAnalysisCollection be limited to 1? I did not find any rule which says that only one 1 CB is allowed. `<element name="supplementaryAnalysisCollection" minOccurs="0" maxOccurs="1">`

Strictly speaking your suspicion is valid, there is no such constraint documented.  I will make an update to it today.

**Comment by blchoy** [comment]
@jkorosi could you take a look at commit [65104a0](https://github.com/wmo-im/iwxxm/pull/312/commits/65104a079fd8671d2801f79af2595bc6d71d056d) to double confirm your suggestions (viz your [comment](https://github.com/wmo-im/iwxxm/pull/312#issuecomment-1367675879) and [PR](https://github.com/wmo-im/iwxxm/pull/314)) have been properly implemented?

**Review by jkorosi — APPROVED** [review]

**Comment by jkorosi** [comment]
It seems OK.

**Pull request merged**
