### PR TITLE
Additional guidance provided

### PR DESCRIPTION
**Pull request by mgoberfield**
Updated TAC-to-XML-Guidance.txt document and example of STNR in AIRMET.

### CODE REVIEW

**Comment by blchoy** [comment]
I have made one more change to the guidance.  @mgoberfield please consider.

**Comment by mgoberfield** [comment]
Keeping in mind that "[t]he regulations are there for us to comply with, and if we believe they are inappropriate we should change them instead of doing what we want". So long as MIE agrees that there can be less than 4 forecast elements in the IWXXM TCA product because of TC dissipation, then your latest revision to the text is fine with me.

**Comment by blchoy** [comment]
> 
> 
> Keeping in mind that "[t]he regulations are there for us to comply with, and if we believe they are inappropriate we should change them instead of doing what we want". So long as MIE agrees that there can be less than 4 forecast elements in the IWXXM TCA product because of TC dissipation, then your latest revision to the text is fine with me.

Can't agree more.  I have made another attempt.  Do you think this is obvious enough?

**Comment by mgoberfield** [comment]
Your last revision is clear enough to me.  Thank you.

**Comment by jkorosi** [comment]
The documentation of **directionOfMotion** and **speedOfMotion** have to be updated, too.  

```XML
	<complexType name="SIGMETEvolvingConditionType">
		<complexContent>
			<extension base="gml:AbstractFeatureType">
				<sequence>
					<element name="geometry" type="iwxxm:AirspaceVolumePropertyType">
						<annotation>
							<documentation>The expected geographic region(s) affected by the reported phenomenon at a particular time (thunderstorms, volcanic ash, etc.).  This geometry covers all combinations of phenomenon historically reported in ICAO Annex 3 / WMO No. 49-2: a boundary with a base and top, a TC centre position, and a VA line with a width</documentation>
						</annotation>
					</element>
					<element nillable="true" name="directionOfMotion" type="iwxxm:AngleWithNilReasonType" minOccurs="0" maxOccurs="1">
						<annotation>
							<documentation>This element refers to the expected direction of movement which the phenomenon is moving towards, .e.g, "moving east". When no movement is expected, this is a http://www.opengis.net/def/nil/OGC/0/inapplicable nilReason and the speedOfMotion will be 0.

This element value is given in degrees from true North. Plane angle unit of measure (uom) is "deg". </documentation>
						</annotation>
					</element>
					<element name="speedOfMotion" type="gml:SpeedType" minOccurs="0" maxOccurs="1">
						<annotation>
							<documentation>The expected speed of movement of a meteorological condition. When no movement is expected, this will have a value of 0 and directionOfMotion will have a http://www.opengis.net/def/nil/OGC/0/inapplicable nilReason.

speedOfMotion can be provided in either two units of measures: "km/h" or "[kn_i]" (knots).</documentation>
						</annotation>
					</element>
```

**Pull request merged**
